import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parse } from '@babel/parser';
import traverseModule from '@babel/traverse';
const traverse = traverseModule.default || traverseModule;
const globals = new Set([
    'module',
    'exports',
    'require',
    'Object',
    'Array',
    'Math',
    'undefined',
    'console',
    'window',
    'document',
    'Element',
    'HTMLElement',
    'Node',
    'URL',
    'setTimeout',
    'clearTimeout',
]);
for (const file of [
    'admin/src/pages/config/system/components/AppConfigTab.tsx',
    'admin/src/pages/config/system/components/ConfigRow.tsx',
    'admin/src/pages/config/system/components/DepositConfigTab.tsx',
    'admin/src/pages/config/system/components/EmailConfigTab.tsx',
    'admin/src/pages/config/system/components/FrontendConfigTab.tsx',
    'admin/src/pages/config/system/components/InviteConfigTab.tsx',
    'admin/src/pages/config/system/components/SafeConfigTab.tsx',
    'admin/src/pages/config/system/components/ServerConfigTab.tsx',
    'admin/src/pages/config/system/components/SiteConfigTab.tsx',
    'admin/src/pages/config/system/components/SubscribeConfigTab.tsx',
    'admin/src/pages/config/system/components/TelegramConfigTab.tsx',
    'admin/src/pages/config/system/components/TicketConfigTab.tsx',
    'admin/src/pages/server/manage/editors/ShadowsocksEditor.tsx',
    'admin/src/pages/server/manage/editors/Shadowsocks/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/Shadowsocks/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/Shadowsocks/SecuritySettings.tsx',
    'admin/src/pages/server/manage/editors/AnyTlsEditor.tsx',
    'admin/src/pages/server/manage/editors/AnyTls/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/AnyTls/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/AnyTls/PaddingScheme.tsx',
    'admin/src/components/order/AssignOrderEditor.tsx',
    'admin/src/components/common/FilterDrawer.tsx',
    'admin/src/components/common/NullableSelectOption.tsx',
    'admin/src/pages/server/manage/editors/HysteriaEditor.tsx',
    'admin/src/pages/server/manage/editors/Hysteria/ObfuscationSettings.tsx',
    'admin/src/pages/server/manage/editors/Hysteria/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/Hysteria/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/ServerEditorRegistry.tsx',
    'admin/src/pages/server/manage/editors/ServerEditorDrawer.tsx',
    'admin/src/pages/server/manage/components/ServerManageActions.tsx',
    'admin/src/pages/server/manage/components/ServerManageColumns.tsx',
    'admin/src/pages/server/manage/components/ServerManageMobileList.tsx',
    'admin/src/pages/server/manage/components/ServerManageToolbar.tsx',
    'admin/src/pages/server/manage/components/ServerNameColumn.tsx',
    'admin/src/pages/server/manage/components/ServerRateColumn.tsx',
    'admin/src/pages/server/manage/components/ServerTypeTag.tsx',
    'admin/src/pages/server/manage/components/ServerManageWorkspace.tsx',
    'admin/src/components/common/PermissionGroupEditor.tsx',
    'admin/src/pages/user/components/SendMailEditor.tsx',
    'admin/src/pages/user/components/UserFilterDrawer.tsx',
    'admin/src/pages/server/manage/editors/types.ts',
    'admin/src/pages/server/manage/editors/Security/TlsSettings.tsx',
    'admin/src/pages/server/manage/editors/Security/TlsAdvancedSettings.tsx',
    'admin/src/pages/server/manage/editors/Security/TlsCertificateSettings.tsx',
    'admin/src/pages/server/manage/editors/Security/TlsRealitySettings.tsx',
    'admin/src/pages/server/manage/editors/Security/EncryptionSettings.tsx',
    'admin/src/components/common/SortableTable.tsx',
    'admin/src/pages/server/manage/editors/TrojanEditor.tsx',
    'admin/src/pages/server/manage/editors/Trojan/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/Trojan/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/Trojan/NetworkSettings.tsx',
    'admin/src/pages/server/manage/editors/TuicEditor.tsx',
    'admin/src/pages/server/manage/editors/Tuic/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/Tuic/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/Tuic/TransportSettings.tsx',
    'admin/src/pages/user/components/UserGenerator.tsx',
    'admin/src/pages/user/components/UserEditor.tsx',
    'admin/src/pages/user/components/UserFormFields.tsx',
    'admin/src/pages/user/components/UserList.tsx',
    'admin/src/pages/user/components/UserDisplayColumns.tsx',
    'admin/src/pages/server/manage/editors/V2NodeEditor.tsx',
    'admin/src/pages/server/manage/editors/V2Node/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolSelectionFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/TransportFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolSpecificFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolSpecific/Hysteria2Fields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolSpecific/TuicFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolSpecific/ShadowsocksFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ProtocolSpecific/VlessFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/V2Node/ChildSettingsPanel.tsx',
    'admin/src/pages/server/manage/editors/VlessEditor.tsx',
    'admin/src/pages/server/manage/editors/VmessEditor.tsx',
    'admin/src/pages/server/manage/editors/Vmess/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/Vmess/NetworkFields.tsx',
    'admin/src/pages/server/manage/editors/Vmess/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/Vmess/ChildSettingsPanel.tsx',
    'admin/src/pages/server/manage/editors/Vmess/DnsSettings.tsx',
    'admin/src/pages/server/manage/editors/Vmess/RuleSettings.tsx',
    'admin/src/pages/server/manage/editors/Vmess/TlsSettings.tsx',
    'admin/src/pages/server/manage/editors/Vless/GeneralFields.tsx',
    'admin/src/pages/server/manage/editors/Vless/RelationshipFields.tsx',
    'admin/src/pages/server/manage/editors/Vless/ChildSettingsPanel.tsx',
    'admin/src/app/Router.tsx',
    'admin/src/config/navigation.tsx',
    'admin/src/layouts/Header/HeaderLayout.tsx',
    'admin/src/layouts/MainLayout/MainLayout.tsx',
    'admin/src/layouts/Sidebar/SidebarLayout.tsx',
    'admin/src/pages/config/payment/PaymentConfigPage.tsx',
    'admin/src/pages/config/payment/components/PaymentNotifyColumn.tsx',
    'admin/src/pages/config/payment/components/PaymentList.tsx',
    'admin/src/pages/config/payment/components/PaymentEditor.tsx',
    'admin/src/pages/config/payment/components/PaymentBasicFields.tsx',
    'admin/src/pages/config/payment/components/PaymentConfigFields.tsx',
    'admin/src/pages/config/payment/components/PaytaroNotice.tsx',
    'admin/src/pages/config/theme/ThemeConfigPage.tsx',
    'admin/src/pages/config/theme/components/ThemeConfigEditor.tsx',
    'admin/src/pages/config/system/SystemConfigPage.tsx',
    'admin/src/pages/dashboard/DashboardPage.tsx',
    'admin/src/pages/dashboard/components/DashboardNavigation.tsx',
    'admin/src/pages/dashboard/components/DashboardOverview.tsx',
    'admin/src/pages/dashboard/components/DashboardServerRank.tsx',
    'admin/src/pages/plan/PlanPage.tsx',
    'admin/src/pages/plan/components/PlanList.tsx',
    'admin/src/pages/plan/components/PlanGroupColumn.tsx',
    'admin/src/pages/plan/components/PlanPriceColumns.ts',
    'admin/src/pages/plan/components/PlanResourceColumns.tsx',
    'admin/src/pages/plan/components/PlanEditor.tsx',
    'admin/src/pages/plan/components/PlanAccessFields.tsx',
    'admin/src/pages/plan/components/PlanBasicFields.tsx',
    'admin/src/pages/plan/components/PlanEditorActions.tsx',
    'admin/src/pages/plan/components/PlanResourceFields.tsx',
    'admin/src/pages/plan/components/PriceFields.tsx',
    'admin/src/pages/coupon/CouponPage.tsx',
    'admin/src/pages/coupon/components/CouponList.tsx',
    'admin/src/pages/coupon/components/CouponColumns.tsx',
    'admin/src/pages/coupon/components/CouponEditor.tsx',
    'admin/src/pages/coupon/components/CouponBasicFields.tsx',
    'admin/src/pages/coupon/components/CouponValueFields.tsx',
    'admin/src/pages/coupon/components/CouponUsageFields.tsx',
    'admin/src/pages/coupon/components/CouponRestrictionsFields.tsx',
    'admin/src/pages/coupon/components/CouponGenerationField.tsx',
    'admin/src/pages/giftcard/GiftcardPage.tsx',
    'admin/src/pages/giftcard/components/GiftcardList.tsx',
    'admin/src/pages/giftcard/components/GiftcardColumns.tsx',
    'admin/src/pages/giftcard/components/GiftcardEditor.tsx',
    'admin/src/pages/giftcard/components/GiftcardBasicFields.tsx',
    'admin/src/pages/giftcard/components/GiftcardValueFields.tsx',
    'admin/src/pages/giftcard/components/GiftcardPlanField.tsx',
    'admin/src/pages/giftcard/components/GiftcardUsageFields.tsx',
    'admin/src/pages/giftcard/components/GiftcardGenerationField.tsx',
    'admin/src/pages/knowledge/KnowledgePage.tsx',
    'admin/src/pages/knowledge/components/KnowledgeList.tsx',
    'admin/src/pages/knowledge/components/KnowledgeColumns.ts',
    'admin/src/pages/knowledge/components/KnowledgeEditor.tsx',
    'admin/src/pages/AdminHomeRedirect.tsx',
    'admin/src/pages/notice/NoticePage.tsx',
    'admin/src/pages/notice/components/NoticeList.tsx',
    'admin/src/pages/notice/components/NoticeColumns.ts',
    'admin/src/pages/notice/components/NoticeEditor.tsx',
    'admin/src/pages/notice/components/NoticeContentFields.tsx',
    'admin/src/pages/notice/components/NoticeMetadataFields.tsx',
    'admin/src/pages/order/OrderPage.tsx',
    'admin/src/pages/order/components/OrderFilterDrawer.tsx',
    'admin/src/pages/order/components/OrderList.tsx',
    'admin/src/pages/order/components/OrderColumns.tsx',
    'admin/src/pages/order/components/OrderListColumns.tsx',
    'admin/src/pages/order/components/OrderDetailModal.tsx',
    'admin/src/pages/order/components/OrderDetailBody.tsx',
    'admin/src/pages/queue/QueuePage.tsx',
    'admin/src/pages/server/group/ServerGroupPage.tsx',
    'admin/src/pages/server/group/components/ServerGroupColumns.tsx',
    'admin/src/pages/server/group/components/ServerGroupList.tsx',
    'admin/src/pages/server/route/ServerRoutePage.tsx',
    'admin/src/pages/server/route/components/RouteActionColumn.ts',
    'admin/src/pages/server/route/components/ServerRouteColumns.ts',
    'admin/src/pages/server/route/components/ServerRouteList.tsx',
    'admin/src/pages/server/route/components/RouteEditor.tsx',
    'admin/src/pages/server/route/components/RouteActionField.tsx',
    'admin/src/pages/server/route/components/RouteBasicFields.tsx',
    'admin/src/pages/server/route/components/RouteMatchField.tsx',
    'admin/src/pages/server/manage/ServerManagePage.tsx',
    'admin/src/pages/ticket/TicketPage.tsx',
    'admin/src/pages/ticket/components/TicketList.tsx',
    'admin/src/pages/ticket/components/TicketColumns.ts',
    'admin/src/pages/ticket/[id].tsx',
    'admin/src/pages/user/UserPage.tsx',
]) {
    const localFile = file.replace(/^admin\//, '');
    test(`${localFile}: references resolve in their lexical scope`, () => {
        const source = readFileSync(new URL('../' + localFile, import.meta.url), 'utf8');
        const ast = parse(source, { sourceType: 'module', plugins: ['jsx', 'typescript'] });
        const missing = [];
        traverse(ast, {
            ReferencedIdentifier(path) {
                if (path.findParent((parent) => parent.node.type.startsWith('TS'))) return;
                if (!globals.has(path.node.name) && !path.scope.hasBinding(path.node.name)) {
                    missing.push(`${path.node.name}:${path.node.loc.start.line}`);
                }
            },
            AssignmentExpression(path) {
                const left = path.node.left;
                if (
                    left.type === 'Identifier' &&
                    !path.scope.hasBinding(left.name) &&
                    !globals.has(left.name)
                )
                    missing.push(left.name);
            },
        });
        assert.deepEqual(missing, []);
        if (/pages\/(user|order)\/.*FilterDrawer/.test(localFile)) {
            assert.match(source, /create(User|Order)FilterFields|orderFilterFields/);
            assert.match(source, /<FilterDrawer\b/);
            assert.doesNotMatch(source, /adobjectAssign/);
        }
    });
}
